In [1]:
import numpy as np

In [3]:
a = np.random.randn(5)
print a

[-1.09433806  0.46609752 -0.99235363 -0.02231429 -0.63894925]


In [4]:
print (a.T)

[-1.09433806  0.46609752 -0.99235363 -0.02231429 -0.63894925]


In [5]:
a = np.random.randn(5,1)
print a

[[ 2.27923041]
 [ 1.73138737]
 [ 0.91079916]
 [ 1.42595846]
 [-0.06668125]]


In [6]:
print (a.T)

[[ 2.27923041  1.73138737  0.91079916  1.42595846 -0.06668125]]


In [7]:
print (a+a.T)

[[ 4.55846081  4.01061777  3.19002956  3.70518887  2.21254915]
 [ 4.01061777  3.46277473  2.64218652  3.15734583  1.66470611]
 [ 3.19002956  2.64218652  1.82159832  2.33675762  0.84411791]
 [ 3.70518887  3.15734583  2.33675762  2.85191692  1.35927721]
 [ 2.21254915  1.66470611  0.84411791  1.35927721 -0.1333625 ]]


In [8]:
print (np.random.randn(1,5))

[[-0.90310188  0.28735599  0.05487945 -0.28018183  1.03509544]]
