In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')
print (env.observation_space, env.action_space)

(Discrete(16), Discrete(4))


In [6]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])
# print(env.observation_space.n, env.action_space.n)

#Set learning parameters
lr = .8
y = .95
num_episodes = 10000

#Create lists to contain total rewards and steps per episode 
rList = []

for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    #The Q-Table learning algorithm
    while j<99:
        j+=1
        #choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment 
        s1, r, d, _ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr * (r + y*np.max(Q[s1,:])-Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [7]:
print "Score over time: " + str(sum(rList)/num_episodes)

Score over time: 0.5538


In [8]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[6.48045869e-02 2.30756186e-03 2.65864760e-03 2.80680989e-03]
 [5.13930097e-04 6.89742685e-04 2.45428074e-04 8.63954487e-02]
 [2.19536193e-03 1.06857935e-03 6.40114479e-04 6.93347001e-02]
 [4.35716443e-04 3.52407680e-05 3.81547633e-04 3.99122128e-02]
 [6.87933602e-02 9.66807731e-04 7.18045018e-04 6.14300347e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.45915031e-02 1.01120063e-07 4.57490586e-05 3.40051256e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.74919494e-04 2.52040097e-04 2.41124257e-04 8.86833575e-02]
 [5.46571199e-04 8.45029563e-02 6.47906380e-04 1.68553409e-03]
 [7.32890220e-02 2.01779628e-04 6.54216234e-05 7.62249024e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.48917827e-03 9.78736833e-05 6.70385512e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.40606398e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [9]:
print rList

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,