In [1]:
import gym
import numpy as np

In [30]:
env = gym.make('FrozenLake-v0')
print (env.observation_space, env.action_space)

(Discrete(16), 4)


In [28]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])
# print(env.observation_space.n, env.action_space.n)

#Set learning parameters
lr = .8
y = .95
num_episodes = 10000

#Create lists to contain total rewards and steps per episode 
rList = []

for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    #The Q-Table learning algorithm
    while j<99:
        j+=1
        #choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment 
        s1, r, d, _ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr * (r + y*np.max(Q[s1,:])-Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [13]:
print "Score over time: " + str(sum(rList)/num_episodes)

Score over time: 0.7126


In [14]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[1.09555046e-01 1.06287013e-02 8.04573785e-03 9.87075231e-03]
 [1.98825712e-03 1.26188952e-04 1.50764989e-03 2.24812940e-01]
 [1.78614738e-01 8.09968150e-03 3.61768819e-03 8.57277225e-03]
 [7.51911077e-03 5.50465337e-04 6.28108707e-03 7.30194440e-03]
 [1.32916602e-01 1.05272774e-04 1.99309931e-03 1.08218767e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.23686238e-04 6.34923856e-05 4.72652014e-02 5.71309199e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.77745744e-03 6.26472207e-04 9.68745262e-03 1.41208185e-01]
 [0.00000000e+00 1.56562268e-01 1.30243420e-03 0.00000000e+00]
 [2.58704572e-01 1.56088723e-04 0.00000000e+00 1.32293615e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.51044409e-03 6.50151118e-01 0.00000000e+00]
 [0.00000000e+00 9.35730687e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.

In [17]:
print rList

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,